// app/terms/page.tsx
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service | Sift',
  description: 'Terms and conditions for using Sift',
};

export default function TermsPage() {
  return (
    <div className="flex flex-col items-center pt-12 pb-16 px-4">
      <div className="w-full max-w-3xl">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm text-stone-500 hover:text-stone-700 mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Sift
        </Link>

        <div className="bg-white rounded-2xl border border-stone-200/80 p-6 md:p-8 shadow-card">
          <h1 className="text-3xl font-serif font-bold text-stone-800 mb-2">Terms of Service</h1>
          <p className="text-stone-500 text-sm mb-6">Last updated: May 19, 2026</p>

          <div className="space-y-4 text-stone-700">
            <p>By using Sift, you agree to these terms.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">1. Use of the service</h2>
            <p>Sift provides AI‑generated article summaries, verdicts, and optional audio. You are responsible for how you use this information. Sift is a tool to assist reading, not a substitute for professional advice.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">2. Account responsibilities</h2>
            <p>You are responsible for maintaining the security of your account. You must be at least 13 years old to use Sift.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">3. Fair use and limitations</h2>
            <p>The free tier has usage limits (e.g., number of sifts per month). Excessive automated use may result in temporary suspension. We reserve the right to modify pricing or features with reasonable notice.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">4. Intellectual property</h2>
            <p>Summaries and insights generated by Sift are yours to use. However, the Sift code, design, and brand belong to Cloud & Clipboard. You may not copy or resell the service.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">5. Disclaimer of warranties</h2>
            <p>Sift is provided as-is. We do not guarantee that summaries will always be accurate or that the service will be uninterrupted.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">6. Limitation of liability</h2>
            <p>To the fullest extent permitted by law, Cloud & Clipboard shall not be liable for any indirect, incidental, or consequential damages arising from your use of Sift.</p>

            <h2 className="text-xl font-semibold text-stone-800 mt-6">7. Changes to these terms</h2>
            <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

            <p className="mt-8 text-sm text-stone-500">If you have any questions, please <Link href="/contact" className="text-accent hover:underline">contact us</Link>.</p>
          </div>
        </div>
      </div>
    </div>
  );
}