// app/terms/page.tsx
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { GlassCard } from '@/components/ui/GlassCard';

export const metadata = {
  title: 'Terms of Service | Sift',
  description: 'Terms and conditions for using Sift',
};

export default function TermsPage() {
  return (
    <main className="flex-1 pt-12 pb-16 px-4 max-w-3xl mx-auto">
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-sm text-surface-400 hover:text-surface-200 mb-6 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Sift
      </Link>

      <GlassCard className="p-6 md:p-8">
        <h1 className="text-3xl font-semibold text-surface-50 mb-2">Terms of Service</h1>
        <p className="text-surface-400 text-sm mb-6">Last updated: May 23, 2026</p>

        <div className="space-y-4 text-surface-200">
          <p>By using Sift, you agree to these terms.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">1. Use of the service</h2>
          <p>We use Groq (for AI summarisation), Supabase (database and authentication), Vercel (hosting), Brevo (email delivery), and ElevenLabs (optional audio). Each service has its own privacy policy. We only share the minimum required data (e.g., article text to Groq, email address to Brevo).</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">2. Account responsibilities</h2>
          <p>You are responsible for maintaining the security of your account. You must be at least 13 years old to use Sift.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">3. Acceptable Use Policy</h2>
          <p>Sift may not be used to process, store, or share:</p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li>Illegal content or links to illegal material.</li>
            <li>Content that promotes violence, hate speech, harassment, or exploitation.</li>
            <li>Content that infringes on intellectual property rights.</li>
            <li>Any material that violates applicable laws or regulations.</li>
          </ul>
          <p className="mt-2">We reserve the right to suspend or terminate accounts that violate this policy and to remove any associated content without notice.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">4. Fair use and limitations</h2>
          <p>The free tier has usage limits (e.g., number of sifts per month). Excessive automated use may result in temporary suspension. We reserve the right to modify pricing or features with reasonable notice.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">5. Intellectual property</h2>
          <p>Summaries and insights generated by Sift are yours to use. However, the Sift code, design, and brand belong to Cloud & Clipboard. You may not copy or resell the service.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">6. Disclaimer of warranties</h2>
          <p>Sift is provided as‑is. We do not guarantee that summaries will always be accurate or that the service will be uninterrupted.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">7. Limitation of liability</h2>
          <p>To the fullest extent permitted by law, Cloud & Clipboard shall not be liable for any indirect, incidental, or consequential damages arising from your use of Sift.</p>

          <h2 className="text-xl font-semibold text-surface-50 mt-6">8. Changes to these terms</h2>
          <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

          <p className="mt-8 text-sm text-surface-400">
            If you have any questions, please{' '}
            <Link href="/contact" className="text-accent-400 hover:underline">
              contact us
            </Link>
            .
          </p>
        </div>
      </GlassCard>
    </main>
  );
}